name: Building with GitHub actions and deploying into EC2 (Tomcat)

on:
    push:
        branches:
            - main

jobs:
    build_and_upload_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository into GitHub Runner
              uses: actions/checkout@v3

            - name: install and setup maven and Java within GitHub Runner
              uses: actions/setup-java@v3
              with: 
                distribution: "adopt"
                java-version: "11"
            
            - name: build artifact with Maven
              run: mvn clean package
            
            - name: upload maven artifact into GitHub Packages
              uses: actions/upload-artifact@v3
              with:
                name: webapp
                path: target/*.war
        
    deploy_artifact:
        runs-on: ubuntu-latest
        needs: build_and_upload_artifact
        steps:
            - name: clone repository into new runner
              uses: actions/checkout@v3

            - name: set up maven within new runner
              uses: actions/setup-java@v3
              with:
                distribution: "adopt"
                java-version: "11"

            - name: download uploaded artifact into new runner
              uses: actions/download-artifact@v3
              with: 
                name: webapp
                path: ~/

            # - name: run sonarqube scan against code
            #   run: |
            #     mvn sonar:sonar \
            #     -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
            #     -Dsonar.host.url=${{ secrets.HOST_URL }} \
            #     -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            - name: push into tomcat server (EC2 Instance)
              run: |
                echo "${{ secrets.KEY_PAIR_FILE }}" > ~/key_pair.pem
                chmod 400 ~/key_pair.pem
                sudo scp -i ~/key_pair.pem -o StrictHostKeyChecking=no ~/*.war ec2-user@${{ secrets.INSTANCE_IP }}:/opt/tomcat9/webapps